### ISSUE TITLE
Still not syncing - but still crashing

### ISSUE THREAD

**Issue by badbandit** [bandapps/bandapps.github.io#12] opened 2016-02-10 19:05 UTC
hi,

i would really love to use your band health bridge but it does not work - even after your "bugfix".

the first sync is faster now, but on the info-page of the app i can see that no data was synced. there is also no data in health. if i start the app after the first sync it crashes (or closes within about one ore two seconds).

on my iphone i have lots of crash reports of the app in the diagnose area.

**Comment by ste777** [comment] 2016-02-10 20:17
Me too...

**Comment by bandapps** [comment] 2016-02-10 20:24
Hey bandit,
Sorry for the trouble. I'll try to diagnose it later tonight and I'll give you an update asap.

Thanks for reporting it

**Comment by bandapps** [comment] 2016-02-11 08:18
Hey bandit, could you email me at johnjustinlee@me.com?

**Comment by badbandit** [comment] 2016-02-11 09:53
Hi John,

how can I help you?

Am Donnerstag, 11. Februar 2016 schrieb BandApps :

> Hey bandit, could you email me at johnjustinlee@me.com
> <javascript:_e(%7B%7D,'cvml','johnjustinlee@me.com');>?
>
>
> Sent from my iPhone
>
> > On Feb 10, 2016, at 11:05 AM, badbandit <notifications@github.com

**Comment by J-L** [comment] 2016-02-11 21:47
Would either of you be willing to log into their Microsoft account through a simulated iOS build on my computer?

**Comment by ste777** [comment] 2016-02-13 10:44
still it does not work, when you work out? thank you

**Comment by Jips1971** [comment] 2016-02-13 16:47
I am also still getting crashes since the update, and as yet no data at all imported
Wondering if I should just get an apple watch :(

**Comment by bandapps** [comment] 2016-02-13 16:58
Hey Jips, 
I'm trying to figure out the root cause- the crashing is caused by not loading data. As for why it's not loading data, is your language set to something other than English in Microsoft health?

Can I organize a teamviewer session on my computer some time today? I would like to see the data coming off the Api.

I'm in utc minus 8 in Vancouver

Best regards

John

**Comment by Jips1971** [comment] 2016-02-13 18:29
Glad to help if I can

**Comment by J-L** [comment] 2016-02-13 21:00
hey Jips, can you add me to Skype: Username xjohnleex

**Comment by J-L** [comment] 2016-02-13 23:03
Hey all, 
Just so you know I had a session with tips today.  The data loaded on my simulator but wouldn't load on his phone.  I have a thought this is time zone related as I have not had any complaints from north america.  

Ill work to fix this as soon as I can make it reproducible.  Best regards

John

**Comment by ste777** [comment] 2016-02-13 23:58
Ho, I use the band in Italy utc roma, with the language set in Italian, perhaps this may be the problem ... I hope we can soon find a solution. I apologize for my English, and I wish you a good job, greetings

**Comment by ste777** [comment] 2016-02-14 00:27
hello, I did a test, setting the time zone on the phone with the area using the app works, bringing to Europe the area is not working, I hope we can serve to find a solution. thank you

**Comment by ste777** [comment] 2016-02-14 00:29
Area USA I meant

**Comment by bandapps** [comment] 2016-02-14 00:29
ste777,

You are a great help! which timezone did you set? Can you show me phone of which place you set it from so I know where to start poking around?

Thank you!

John

**Comment by ste777** [comment] 2016-02-14 01:01
I set the time zone in my phone, in settings / date and time / and I put the region Americas precisely Vancouver. I do not know how to post the screenshot to show you ...

**Comment by ste777** [comment] 2016-02-14 01:02
My phone is iPhone 6 with iOS 9.2.1

**Comment by J-L** [comment] 2016-02-14 01:55
Hey @ste777 @Jips1971 could you email me your email addresses at johnjustinlee@me.com

I think i found the bug and can supply a test build to try out.  Thanks a lot all, I know its taken a little more time then I would like to find a fix for it.

For your interest: the bug appears to be caused by the '+' sign caused by timezones ahead of UTC being encoded in the get parameter of the string.

Thanks

John

**Comment by Jips1971** [comment] 2016-02-14 05:12
James@Blonden.co.uk

Glad you are making progress

**Comment by ste777** [comment] 2016-02-14 13:42
Good!!
stefano.fascina@gmail.com

**Comment by ste777** [comment] 2016-02-14 13:58
Inviato da  iPhone

**Comment by Jips1971** [comment] 2016-02-14 15:10
Test version installed and working absolutely fine.  Synced from Nov 15 to today with no issues

**Comment by badbandit** [comment] 2016-02-14 15:59
hi,

i can confirm that it works now. i am happy now and thank you for your
great support.

one question: how does apple health behave, if i sync the data for activity
energy from the band and runtastic? are both values added to each other?
i am asking, because i track my sports with both at the same time, but
runtastic shows way less energy used.

dennis

Am Sonntag, 14. Februar 2016 schrieb John Justin Lee :

**Comment by bandapps** [comment] 2016-02-14 17:03
Great, thanks for everyone's help in tracking it down.

Dennis, to answer your question, if you go to share data for the relevant apple health item, the source on top is the source that is used. You can reorder them anyway you want. 

I'll be pushing an update into the review queue soon.

Thanks

**Comment by badbandit** [comment] 2016-02-14 17:10
hi,

there is a problem with the data. at least with my data i discovered, that
there are many days missing in the STEPS area. at lest every second day is
missing, sometimes 3-4 days - sometime um to 9 days. the data in the other
area seems to be complete.

and the amount of steps i made today is wrong with the current sync at the
moment. i made over 5400 steps today and the sync gives me 4200.

perhaps you should wait with the official update.

2016-02-14 18:03 GMT+01:00 BandApps <notifications@github.com>:

**Comment by ste777** [comment] 2016-02-14 17:19
I can not do the tests with the build 1.2 (13) tells me not available

**Comment by badbandit** [comment] 2016-02-14 17:21
did you receive the invite for testing the beta? if yes, you have to follow the instructions and after your uuid has been added, you can install the beta.

**Comment by ste777** [comment] 2016-02-14 17:26
I followed all the steps but maybe I did something wrong ... now I deleted everything but does not make me try again, how can I do? I apologize to my inability

**Comment by ste777** [comment] 2016-02-14 17:41
you can try again to send the beta?
Thanks

**Comment by bandapps** [comment] 2016-02-14 17:43
Its incoming!  I think you switched the phone you are using?  Every there is a new device I need to add in the did before i build it, or you won’t be able to run it.

**Comment by ste777** [comment] 2016-02-14 17:56
finally it works! You've been a great help, I am very happy, thank you so much of your time, a warm greeting to you and to all Italy

**Comment by badbandit** [comment] 2016-02-14 18:03
no, v1.2(14) makes everything worse. v.1.2(13) was way better!

**Comment by bandapps** [comment] 2016-02-14 18:05
All i did was remove the ask for notifications! (Im not using them, Im trying to use background fetch)

**Comment by ste777** [comment] 2016-02-14 18:06
V.1.2(13) I failed to install,

**Comment by ste777** [comment] 2016-02-14 18:11
version 1.2 (14) works to me

**Comment by badbandit** [comment] 2016-02-14 18:22
apple health seems to be calculating a lot for a while. i check 14 again.

**Comment by bandapps** [comment] 2016-02-14 18:27
Its actually the interface between Apple Health and the world.   If you load quite a bit of time into apple health, you can see for a couple minutes later that the data is still being imported.  Quite interesting actually. I thought it would be instantaneous.  In fact, the original app took longer because… if you close Band Health Bridge too quickly after it is done I think the queue between the apps gets killed. Not that I can prove any of this, but its my observation on it anyways.

**Comment by badbandit** [comment] 2016-02-14 18:46
ok, 14 works like 13. sync is working, but many days of the steps are missing.

[https://www.dropbox.com/s/dvt0uy1ds0d62sp/IMG_3635.PNG?dl=0](url)

can you see the screenshot?

ignoe the past 2 weeks, bacause the band needed to be repaired (although the past 2 days are missing).

**Comment by badbandit** [comment] 2016-02-16 15:45
any news on bugfixing? there still many, many days of steps missing.

**Comment by bandapps** [comment] 2016-02-16 16:04
Can you send me a picture of the data shared page and data points list page?

**Comment by ste777** [comment] 2016-02-16 16:56
Hello! I don't have any bug...if I understand it I send you the photo request...

Inviato da  iPhone

> Il giorno 16 feb 2016, alle ore 17:04, BandApps <notifications@github.com> ha scritto:
> 
> Can you send me a picture of the data shared page and data points list page?
> 
> Sent from my iPhone
>

**Comment by J-L** [comment] 2016-02-16 17:16
Hey Ste, Bandit, Im closing this ticket with the release of 1.2.  Bandit, can you post the data into the missing data ticket I've created?

**Closed by J-L** 2016-02-16 17:16 UTC
Labels: BandHealthBridge, bug
